language: go
go:
- 1.11.5
script:
- go test ./*/
- env GOOS="darwin" GOARCH="amd64" go build -o game-darwin-amd64 .
- env GOOS="windows" GOARCH="amd64" go build -o game-windows-amd64.exe .
- env GOOS="linux" GOARCH="arm" go build -o game-linux-arm .
- env GOOS="linux" GOARCH="amd64" go build -o game-linux-amd64 .

env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: P1+Qht9ounwjMZEW26ihUHe5NnRncha3A66iz9y5jRyhfzKOafUy3jFu/XUjopMRu49HrYtZNBFuWqi21zYLzomwBnDaO4jAwjv3IAirE673Pb69ItS5yUhK9VZTxKCGhlJ/ozHoOZLbMzKWb28NXtb46jfCVA86T6e6XIIjnQVOyvg3SgI21HVe0XAgRKcaWvu6mxd6MK8y8eoSWPmRRemi5HSSA2PqOZC1/P3Ifcf5k5S2vVWFcRKLSOHk8gzRDhtY4s2cWsE0luE5idAmACKlHv50CPyUbF4gWn+ohWN/KFRpVI9F4KsMsBr5ZR3DOw4vsXCHbfq75TcZg2qNvNECD5BRqLGRjgsLVp2+3Uo1HukC985c2fefwvllLc6CVrYJuDVWJ59Lbds0A7Ce64JsisZGSZcx6cIfE6WIdGlVlm6c4iPjwsckBn6PU7bPwB+H7WEWA66JzFaT2vfNYMBgx0frhPFSqBUnQbhETlJCa0cFvDdZukv1dYkBz/N3Gk+5rWOvFpr/vnvGwJ90DqFk30MCQSx63wH50KLDJbibcw4ZkWHvKO4PKbgjEHF7y1zzqJEcSwxUtbn9HmmnrexpLRx+Gj3/0h09rhkeiSWryLe8+NeOxUBPg8qw6Fezh52Y47Aj5w1Y4132TVy9aMKBeJgN7+tXjx0KXO5K3YM=
  file:
    - "game-darwin-amd64"
    - "game-windows-amd64.exe"
    - "game-linux-arm"
    - "game-linux-amd64"
  on:
    branch: master
    repo: chrisdobbins/linkedin-reach
    tags: true
