language: go
go:
- 1.12
env:
- GO111MODULE=on
before_deploy:
- env GOOS="darwin" GOARCH="amd64" go build -o game-darwin-amd64 .
- env GOOS="windows" GOARCH="amd64" go build -o game-windows-amd64.exe .
- env GOOS="linux" GOARCH="arm" go build -o game-linux-arm .
- if [$
- env GOOS="linux" GOARCH="amd64" go build -o game-linux-amd64 .
- go mod vendor
deploy:
- provider: heroku
  api_key:
    secure: rMGJiXPN11xw9ZaZlqP66kS5WDQF1FcrsDrBu3qQK6PqxFSpp3ukwejaYte21pMug4tcgq8DPIu31RO8uXcEJGo6rnkPodZdxuxBepBGxaHuNaSuBcO753msPXEb06tnntdGMIMoHvqPu13g9ENPx6O58Fh/hvMa2DXBsVkZyD5WgwR8uEHjSNiJ+dDZQoKQQFV9Ns8myzfsimoQrfyzovu6QZWywYMJnZ6K/DNQJ/ilciZYaQl+pGRy+Ma4yb5u07qf31ocqi6HXaaB7AQOL5BjULbhGbH/qS6NAWOenIGUi0lmN+tp9d+IDYglMk7u00FwKLYcwlwPXN+sTapmBF/WTGErOkiQm/uIPftWv+MOum81yxpWPqQ2t/w/46iWmLP77kpInOqL1p6485q82XH0DKtQS/4NaHgbdg0MOZvp16acIEQndlZ75Pi9D4rdr8+bM8jSgkjvzdd4ykcAnPJRpTyKYm0lbzf4vjh7gj+qT+5XhtLSYjzi2QEYQ+I4fkF9quLrPSqXUbbl29tEVrQGyllh2+wAY5jA+xDkk34ARIdxHmTUTrOZompxTnwByJfVSPeUix1PWGwtr9WHdvUfKmg4tceYCP//AoKe4e4l5ZqVWkWk1Qe0ihyKiMIbsBfIsQTn7ounGzEN2VuihLXLqEAKfLHupZBpRe3fpCA=
  app: limitless-bastion-18713
  on:
    branch: master
    tags: true
  skip_cleanup: true
- provider: releases
  on:
    branch: master
    repo: chrisdobbins/linkedin-reach
    tags: true
  api_key:
    secure: P1+Qht9ounwjMZEW26ihUHe5NnRncha3A66iz9y5jRyhfzKOafUy3jFu/XUjopMRu49HrYtZNBFuWqi21zYLzomwBnDaO4jAwjv3IAirE673Pb69ItS5yUhK9VZTxKCGhlJ/ozHoOZLbMzKWb28NXtb46jfCVA86T6e6XIIjnQVOyvg3SgI21HVe0XAgRKcaWvu6mxd6MK8y8eoSWPmRRemi5HSSA2PqOZC1/P3Ifcf5k5S2vVWFcRKLSOHk8gzRDhtY4s2cWsE0luE5idAmACKlHv50CPyUbF4gWn+ohWN/KFRpVI9F4KsMsBr5ZR3DOw4vsXCHbfq75TcZg2qNvNECD5BRqLGRjgsLVp2+3Uo1HukC985c2fefwvllLc6CVrYJuDVWJ59Lbds0A7Ce64JsisZGSZcx6cIfE6WIdGlVlm6c4iPjwsckBn6PU7bPwB+H7WEWA66JzFaT2vfNYMBgx0frhPFSqBUnQbhETlJCa0cFvDdZukv1dYkBz/N3Gk+5rWOvFpr/vnvGwJ90DqFk30MCQSx63wH50KLDJbibcw4ZkWHvKO4PKbgjEHF7y1zzqJEcSwxUtbn9HmmnrexpLRx+Gj3/0h09rhkeiSWryLe8+NeOxUBPg8qw6Fezh52Y47Aj5w1Y4132TVy9aMKBeJgN7+tXjx0KXO5K3YM=
  file:
  - game-darwin-amd64
  - game-windows-amd64.exe
  - game-linux-arm
  - game-linux-amd64
  skip_cleanup: true
